apiVersion: v1
kind: Pod
metadata:
  name: stayorgo-pod
  labels:
    app: stayorgo
spec:
  containers:
    - name: stayorgo
      image: stayorgo:0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64M"
          cpu: "250m"
        limits:
          memory: "64M"
          cpu: "250m"
      env:
        - name: REDIS
          value: "redis"
        - name: PERSON
          value: "Fredrick"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
  restartPolicy: OnFailure