apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayorgo
  labels:
    app: stayorgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stayorgo
  template:
    metadata:
      name: stayorgo
      labels:
        app: stayorgo
    spec:
      containers:
        - name: stayorgo
          image: stayorgo:0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /hello
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /hello
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "64M"
              cpu: "250m"
            limits:
              memory: "64M"
              cpu: "250m"
          env:
             - name: REDIS
               value: redis
             - name: PERSON
               value: Luke
             - name: POD_NAME
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: stayorgo-service
  labels:
    app: stayorgo
spec:
  type: NodePort #cluster port expose for localhost routing
  ports:
    - port: 8080  # The port the service is exposed on
      targetPort: 8080  # The target port on the pods, adjust as necessary
      nodePort: 30007 #30000-32767 reserved for K8s
      protocol: TCP
      name: http
  selector:
    app: stayorgo  # Must match labels of the pods you want to target