version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  stayorgo:
    image: stayorgo:0.1
    ports:
      - "8080:8080"
    environment:
      PERSON: foouser
      PORT: 8080
      REDIS: redis
    depends_on:
      - redis
volumes:
  redis_data: